package tapir.pokemon;

public enum SwapStatus {
    AWAITING_USER_TWO_SWAP_GRANT, FIRST_USER_OFFER, SECOND_USER_OFFER,
    BOTH_ACCEPTED_POKEMON_SELECT, FIRST_USER_ACCEPTED_EXCHANGE, DECLINED, WAITING_FOR_POKEMON_ACCEPT
}
